AWSTemplateFormatVersion: '2010-09-09'
Description: Pipeline using CodePipeline and CodeBuild for continuous delivery of a single-page application to S3
Parameters:
  RootDomainName:
    Type: String
    Description: Domain name for your website (example.com)
    Default: "ethanbergstrom.com"
  TTL:
    Type: String
    Description: Domain TTL
    Default: 600
  GitHubUser:
    Type: String
    Description: GitHub User
    Default: "ethanbergstrom"
  SiteGitHubRepo:
    Type: String
    Description: Site GitHub Repo to pull from. Only the Name. not the URL
    Default: "website"
  SiteGitHubBranch:
    Type: String
    Description: Site GitHub Branch
    Default: "master"
  EnviroGitHubRepo:
    Type: String
    Description: Enviro GitHub Repo to pull from. Only the Name. not the URL
    Default: "enviro"
  EnviroGitHubBranch:
    Type: String
    Description: Enviro GitHub Branch
    Default: "master"
  GitHubToken:
    NoEcho: true
    Type: String
    Description: Secret. It might look something like 9b189a1654643522561f7b3ebd44a1531a4287af OAuthToken with access to Repo. Go to https://github.com/settings/tokens
  BuildType:
    Type: String
    Default: "LINUX_CONTAINER"
    Description: The build container type to use for building the app
  BuildComputeType:
    Type: String
    Default: "BUILD_GENERAL1_SMALL"
    Description: The build compute type to use for building the app
  SiteBuildImage:
    Type: String
    Default: "aws/codebuild/ubuntu-base:14.04"
    Description: The build image to use for building the site
  EnviroBuildImage:
    Type: String
    Default: "aws/codebuild/nodejs:6.3.1"
    Description: The build image to use for building the Node Lambda functions
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Site Configuration"
        Parameters:
          - RootDomainName
          - TTL
      - Label:
          default: "GitHub Configuration"
        Parameters:
          - GitHubToken
          - GitHubUser
          - SiteGitHubRepo
          - SiteGitHubBranch
          - EnviroGitHubRepo
          - EnviroGitHubBranch
      - Label:
          default: "Build Configuration"
        Parameters:
          - BuildType
          - BuildComputeType
          - SiteBuildImage
          - EnviroBuildImage
    ParameterLabels:
      RootDomainName:
        default: Domain name for your website (example.com)
      TTL:
        default: Domain TTL
      GitHubToken:
        default: GitHub OAuth2 Token
      GitHubUser: 
        default: GitHub User/Org Name
      SiteGitHubRepo: 
        default: Site GitHub Repository Name
      SiteGitHubBranch: 
        default: Site GitHub Branch Name
      EnviroGitHubRepo: 
        default: Enviro GitHub Repository Name
      EnviroGitHubBranch: 
        default: Enviro GitHub Branch Name
      BuildType: 
        default: CodeBuild type
      BuildComputeType: 
        default: CodeBuild instance type
      BuildImage: 
        default: Site CodeBuild image
      BuildImage: 
        default: Enviro CodeBuild image
Mappings:
  RegionMap:
    us-east-1:
      S3hostedzoneID: Z3AQBSTGFYJSTF
      websiteendpoint: s3-website-us-east-1.amazonaws.com
    us-west-1:
      S3hostedzoneID: Z2F56UZL2M1ACD
      websiteendpoint: s3-website-us-west-1.amazonaws.com
    us-west-2:
      S3hostedzoneID: Z3BJ6K6RIION7M
      websiteendpoint: s3-website-us-west-2.amazonaws.com
    eu-west-1:
      S3hostedzoneID: Z1BKCTXD74EZPE
      websiteendpoint: s3-website-eu-west-1.amazonaws.com
    ap-southeast-1:
      S3hostedzoneID: Z3O0J2DXBE1FTB
      websiteendpoint: s3-website-ap-southeast-1.amazonaws.com
    ap-southeast-2:
      S3hostedzoneID: Z1WCIGYICN2BYD
      websiteendpoint: s3-website-ap-southeast-2.amazonaws.com
    ap-northeast-1:
      S3hostedzoneID: Z2M4EHUR26P7ZW
      websiteendpoint: s3-website-ap-northeast-1.amazonaws.com
    sa-east-1:
      S3hostedzoneID: Z31GFT0UA1I2HV
      websiteendpoint: s3-website-sa-east-1.amazonaws.com
Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: codebuild-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"
          Version: '2012-10-17'
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codepipeline.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: codepipeline-service
        PolicyDocument:
          Statement:
          - Action:
            - codebuild:*
            Resource: "*"
            Effect: Allow
          - Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:GetBucketVersioning
            Resource: "*"
            Effect: Allow
          - Action:
            - s3:PutObject
            Resource:
            - arn:aws:s3:::codepipeline*
            Effect: Allow
          - Action:
            - s3:*
            - cloudformation:*
            - iam:PassRole
            Resource: "*"
            Effect: Allow
          Version: '2012-10-17'
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref RootDomainName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
  WWWBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub www.${RootDomainName}
      AccessControl: BucketOwnerFullControl
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref SiteBucket
  DNSZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref RootDomainName
  ApexRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref RootDomainName
      HostedZoneId: !Ref DNSZone
      Type: A
      Comment: Zone apex
      AliasTarget:
        DNSName: !FindInMap [ RegionMap, !Ref 'AWS::Region', websiteendpoint]
        HostedZoneId: !FindInMap [ RegionMap, !Ref 'AWS::Region', S3hostedzoneID]
  WWWRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub "www.${RootDomainName}"
      HostedZoneId: !Ref DNSZone
      Type: CNAME
      TTL: !Ref TTL
      ResourceRecords: 
      - !GetAtt WWWBucket.DomainName        
  EnviroBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
  PipelineBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
  CodeBuildDeploySite:
    Type: AWS::CodeBuild::Project
    DependsOn: CodeBuildRole
    Properties:
      Name: !Sub ${AWS::StackName}-DeploySite
      Description: Deploy site to S3
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: !Ref BuildType
        ComputeType: !Ref BuildComputeType
        Image: !Sub ${SiteBuildImage}
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.1
          phases:
            post_build:
              commands:
                - aws s3 cp --recursive --acl public-read ./ s3://${RootDomainName}/ 
      TimeoutInMinutes: 10
  CodeBuildEnviro:
    Type: AWS::CodeBuild::Project
    DependsOn: CodeBuildRole
    Properties:
      Name: !Sub ${AWS::StackName}-Enviro
      Description: Deploy Enviro
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: !Ref BuildType
        ComputeType: !Ref BuildComputeType
        Image: !Sub ${EnviroBuildImage}
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          phases:
            install:
              commands:
                - echo Installing AWS SAM to run deployment commands
                - npm config set unsafe-perm=true
                - npm install -g aws-sam-local
            post_build:
              commands:
                - echo Packaging and deploying SAM template to CloudFormation
                - ls -l
                - sam package --template-file template.yaml --s3-bucket ${EnviroBucket}  --output-template-file packaged.yaml
                - cat packaged.yaml
                - sam deploy --template-file packaged.yaml --stack-name ${AWS::StackName}-Enviro --capabilities CAPABILITY_IAM
      TimeoutInMinutes: 10
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
      - Name: Source
        Actions:
        - InputArtifacts: []
          Name: SiteSource
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Version: '1'
            Provider: GitHub
          OutputArtifacts:
          - Name: SiteSourceOutput
          Configuration:
            Owner: !Ref GitHubUser
            Repo: !Ref SiteGitHubRepo
            Branch: !Ref SiteGitHubBranch
            OAuthToken: !Ref GitHubToken
          RunOrder: 1
        - InputArtifacts: []
          Name: EnviroSource
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Version: '1'
            Provider: GitHub
          OutputArtifacts:
          - Name: EnviroSourceOutput
          Configuration:
            Owner: !Ref GitHubUser
            Repo: !Ref EnviroGitHubRepo
            Branch: !Ref EnviroGitHubBranch
            OAuthToken: !Ref GitHubToken
          RunOrder: 1
      - Name: Deploy
        Actions:
        - Name: SiteArtifact
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: '1'
            Provider: CodeBuild
          InputArtifacts:
          - Name: SiteSourceOutput
          OutputArtifacts:
          - Name: SiteDeployOutput
          Configuration:
            ProjectName: !Ref CodeBuildDeploySite
          RunOrder: 1
        - Name: EnviroArtifact
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: '1'
            Provider: CodeBuild
          InputArtifacts:
          - Name: EnviroSourceOutput
          OutputArtifacts:
          - Name: EnviroDeployOutput
          Configuration:
            ProjectName: !Ref CodeBuildEnviro
          RunOrder: 1
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineBucket
Outputs:
  PipelineUrl:
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${Pipeline}
    Description: CodePipeline URL
  SiteUrl:
    Value: !GetAtt [SiteBucket, WebsiteURL]
    Description: S3 Website URL
